namespace: ingress-traefik

traefik:
  service:
    type: LoadBalancer

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress-traefik

  ports:
    web:
      redirectTo:
        port: websecure
    websecure:
      tls:
        certResolver: letsencrypt-traefik
      forwardedHeaders:
        insecure: true
      proxyProtocol:
        insecure: true
      http3:
        enabled: true

  logs:
    general:
      level: INFO
    access:
      enabled: true
      fields:
        general:
          defaultMode: keep
        headers:
          defaultMode: keep

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: [websecure]
      matchRule: Host(`dashboard.traefik.k8s.traefik.webgrip.nl`)
      middlewares:
        - name: traefik-dashboard-auth
        - name: special-ip-whitelist

  extraObjects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: traefik-dashboard-auth-secret
      type: kubernetes.io/basic-auth
      stringData:
        username: admin
        password: changeme

    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: traefik-dashboard-auth
      spec:
        basicAuth:
          secret: traefik-dashboard-auth-secret

    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: traefik-dashboard-auth
      spec:
        basicAuth:
          secret: traefik-dashboard-auth-secret

    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: special-ip-whitelist
      spec:
        ipAllowList:
          sourceRange:
            - 188.89.91.129/32
