namespace: ingress-traefik

traefik:
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"

  globalArguments: # This is to disable the default --global.sendanonymoususage flag
    - "--global.checknewversion"

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress-traefik

  ports:
    web:
      redirectTo:
        port: websecure
    websecure:
      forwardedHeaders:
        insecure: true
        trustedIPs:
          - 0.0.0.0/0
      proxyProtocol:
        insecure: true
        trustedIPs:
          - 0.0.0.0/0
      http3:
        enabled: true

  logs:
    general:
      level: INFO
    access:
      enabled: true
      fields:
        general:
          defaultMode: keep
        headers:
          defaultMode: keep

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: [websecure]
      matchRule: Host(`dashboard.traefik.k8s.traefik.webgrip.nl`)
      middlewares:
        - name: traefik-dashboard-auth
