apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
