apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      {{- .Values.selectorLabels | toYaml | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 10s