replicaCount: 1

image:
  repository: docker.io/{{ .Values.projectName }}
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  hosts:
    - host: application.webgrip.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls: []

configMap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

resources:
 requests:
   cpu: 100m
   memory: 128Mi
 limits:
   cpu: 200m
   memory: 256Mi

selectorLabels:
  app: frontend
