apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quote-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quote-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quote-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  template:
    metadata:
      labels:
        {{- include "quote-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: quote
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
