apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.client_id | b64enc | quote }}
  client-secret: {{ .Values.client_secret | b64enc | quote }}


