namespace: backend

replicaCount: 1

image:
  repository: jmalloc/echo-server
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "200m"
    memory: "100Mi"

service:
  type: ClusterIP
  port: 80

deployment:
  strategy:
    type: RollingUpdate

ingress:
  enabled: true
  className: nginx
  host: echo.k8s.DOMAIN.nl
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: letsencrypt-nginx
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
