replicaCount: 2

image:
  repository: traefik
  tag: "3.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

dashboard:
  enabled: true
  domain: dashboard.traefik.staging.aws.webgrip.nl

ingressRoute:
  enabled: true
  domain: traefik.staging.aws.webgrip.nl

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  tls:
    - hosts:
        - "example.com"
      secretName: "example-tls-secret"
  hosts:
    - host: "example.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
