namespace: grafana-stack

replicaCount: 1

image:
  repository: "foxdalas/openai-exporter"
  tag: "v0.0.11"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9185

serviceMonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 10s

useHashSuffix: false
