{
 "title": "ARC Performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SystemNamespace",
    "label": "ARC System Namespace",
    "query": {
     "query": "label_values(gha_controller_running_listeners,namespace)"
    }
   },
   {
    "name": "Scaleset",
    "label": "Scale Set",
    "query": {
     "query": "label_values(gha_desired_runners,actions_github_com_scale_set_name)"
    }
   },
   {
    "name": "RunnerNamespace",
    "label": "Runner Namespace",
    "query": {
     "query": "label_values(gha_desired_runners{actions_github_com_scale_set_name=~\"$Scaleset\"},namespace)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Startup Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(sum by(le) ((gha_job_startup_duration_seconds_bucket{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"})) -\nsum by(le) ((gha_job_startup_duration_seconds_bucket{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"} offset $__rate_interval)), 0)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (gha_job_execution_duration_seconds_bucket{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"}) - sum by (le) (gha_job_execution_duration_seconds_bucket{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"} offset $__rate_interval)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{name=\"ephemeral-runner-controller\", namespace=\"$SystemNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Execution Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_job_execution_duration_seconds_sum{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"}) by (job_workflow_ref) / sum ((gha_job_execution_duration_seconds_count{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"}) or vector(1)) by (job_workflow_ref) > 0",
     "legendFormat": "{{job_workflow_ref}}"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "gauge",
   "description": "Number of runners in a Running state",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gha_controller_running_ephemeral_runners{name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Runners",
   "type": "gauge",
   "description": "Registered runners without jobs",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_idle_runners{actions_github_com_scale_set_name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Runners",
   "type": "gauge",
   "description": "Number of runners that are pending (ContainerCreating)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_pending_ephemeral_runners{name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Runners",
   "type": "gauge",
   "description": "Number of runners desired by the scale set",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_desired_runners{actions_github_com_scale_set_name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "gauge",
   "description": "The number of active job listeners",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_running_listeners)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(max_over_time(gha_controller_running_listeners[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered Runners",
   "type": "gauge",
   "description": "The number of runners registered for processing queued jobs",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_registered_runners{actions_github_com_scale_set_name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assigned Jobs",
   "type": "gauge",
   "description": "The number of jobs assigned to the runner set. ",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_assigned_jobs{namespace=~\"$RunnerNamespace\", actions_github_com_scale_set_name=~\"$Scaleset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gha_desired_runners{namespace=~\"$RunnerNamespace\", actions_github_com_scale_set_name=~\"$Scaleset\"}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "gauge",
   "description": "The number of workflow jobs currently executing",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (gha_running_jobs{actions_github_com_scale_set_name=~\"$Scaleset\", actions_github_com_scale_set_namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Pod Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$RunnerNamespace\"}) != 0 or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$RunnerNamespace\"}) != 0 or vector(0)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$RunnerNamespace\", reason=\"Completed\"}) != 0 or vector(0)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$RunnerNamespace\", reason=\"Error\"}) != 0 or vector(0)",
     "legendFormat": "Error"
    },
    { "expr": "sum(gha_desired_runners) > 0", "legendFormat": "__auto" }
   ]
  }
 ]
}