namespace: arc-systems-k8s

gha-runner-scale-set-controller:
  replicaCount: 1

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cpu"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "dedicated"
                operator: "In"
                values:
                  - "cpu"
  metrics:
    controllerManagerAddr: ":8080"
    listenerAddr: ":8080"
    listenerEndpoint: "/metrics"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
