apiVersion: v2
name: tempo-chart
description: A Helm chart for a Tempo instance (non-distributed)
version: 0.1.0
dependencies:
  - name: alloy
    version: 0.12.5
    repository: https://grafana.github.io/helm-charts
