namespace: grafana-stack

alloy:
  alloy:
    mounts:
      varlog: true
      dockercontainers: true
    stabilityLevel: "experimental"
    extraPorts:
      - name: "http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
      - name: "grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
    configMap:
      create: true
      content: |-
        otelcol.receiver.otlp "default" {
          grpc {
            endpoint = "0.0.0.0:4317"
          }
          http {
            endpoint = "0.0.0.0:4318"
          }

          output {
            metrics = [otelcol.exporter.prometheus.default.input]
            logs    = [otelcol.exporter.loki.default.input]
            traces  = [otelcol.exporter.otlp.tempo.input]
          }
        }

        otelcol.exporter.prometheus "default" {
          forward_to = [prometheus.remote_write.incluster.receiver]
        }

        otelcol.exporter.loki "default" {
          forward_to = [loki.write.incluster.receiver]
        }

        otelcol.exporter.otlp "tempo" {
          client {
            endpoint = "tempo.grafana-stack.svc.cluster.local:4317"
            tls {
              insecure = true
              insecure_skip_verify = true
            }
          }
        }

        prometheus.remote_write "incluster" {
          endpoint {
            url = "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090/api/v1/write"
          }
        }

        loki.write "incluster" {
          endpoint {
            url = "loki.grafana-stack.svc.cluster.local:3100"
          }
        }


    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m

  controller:
    type: daemonset

  configReloader:
    enabled: true

  service:
    enabled: true
    type: ClusterIP
