namespace: kube-prometheus-stack

kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password
#    persistence:
#      enabled: true
#      size: 10Gi
#    service:
#      type: ClusterIP

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 7d
      podMonitorSelector:
        matchLabels:
          app: gha-runner-pod-monitor
      serviceMonitorSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
      additionalScrapeConfigs: |
        - job_name: 'annotation-scrape'
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Only keep pods that have prometheus.io/scrape=true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: "true"
            # Use the annotation value for the metrics path, if available
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: "(.+)"
            # Replace the default port with the value from the annotation
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: "(.+)"
              replacement: "$1"

#      storageSpec:
#        volumeClaimTemplate:
#          spec:
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 10Gi

  alertmanager:
    enabled: false
#    alertmanagerSpec:
#      storage:
#        volumeClaimTemplate:
#          spec:
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 2Gi

  # node-exporter & kube-state-metrics are installed automatically with defaults
  # but you can override them if you like:
#  kube-state-metrics:
#    rbac:
#      create: true

#  nodeExporter:
#    tolerations: []
    # ...
