namespace: kube-prometheus-stack

kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password
#    persistence:
#      enabled: true
#      size: 10Gi
#    service:
#      type: ClusterIP

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 7d
      podMonitorSelector:
        matchLabels:
          app: gha-runner-pod-monitor
#      storageSpec:
#        volumeClaimTemplate:
#          spec:
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 10Gi

  alertmanager:
    enabled: false
#    alertmanagerSpec:
#      storage:
#        volumeClaimTemplate:
#          spec:
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 2Gi

  # node-exporter & kube-state-metrics are installed automatically with defaults
  # but you can override them if you like:
#  kube-state-metrics:
#    rbac:
#      create: true

#  nodeExporter:
#    tolerations: []
    # ...
