apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.admin_user | b64enc | quote }}
  admin-password: {{ .Values.admin_password | b64enc | quote }}

