{{- if .Values.middlewares }}
{{- range $name, $middleware := .Values.middlewares }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: traefik-chart-{{ $.Chart.Version }}
    app.kubernetes.io/name: traefik-chart
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: Helm
spec:
  {{- toYaml $middleware | nindent 2 }}
---
{{- end }}
{{- end }}
