apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "traefik-chart.selectorLabels" . | nindent 4 }}
