namespace: ENC[AES256_GCM,data:FB8g9R7rnSu91dSJEA==,iv:O5i5Ur1FaMlAbnzVn2DrzlPNwNprzc5Gx3qylUVfmSs=,tag:H3bU7Q0aiT+9uJi7mcVMFQ==,type:str]
admin_user: ENC[AES256_GCM,data:6hFTwFU=,iv:37adCr12Q3PFMR+C7L8Xzg1YK/TxrbpM8sxguJ1BkfM=,tag:INvPjJXPMewmehfDptuSXg==,type:str]
admin_password: ENC[AES256_GCM,data:NzZqnZGRj/k+Ayfg30w/aZXpE34Sja5cDQ==,iv:w5iH/dOyWdE+UFgYNhuzbFCfb0oD/HdLDNLVNVvBEBA=,tag:1UZ1JRAhWvRR0+f7UQMx3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekgn75dxgx0wlcd60lm0u7quc7rvukcecdj2l82zzw58y7pnhsks40d6d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSlNIaHFVSTQza2xCWmdw
            TkExSUdGTjBtU0gxbjg1cVRWMWJydnNzcmxZCmVDQTMvRmtxczlNdlEvekxuUUxy
            ZmVhZGFZdTB0ei9FZnZlU080R05JZzAKLS0tIGw5VFFvdTFlQlVSb2lBTmtrN29p
            MjlqU1BLZ3d6aERRTCtldUFOWUFBRW8KY99X9fn6cUNUTx7XowO/accf5Sftmmdi
            /yOQnWvDNBf8qPeqcAQZ6/h0Wa7QUGwEyStVEtpzaOZElFoMgVZVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-01T12:52:00Z"
    mac: ENC[AES256_GCM,data:FedhsbJj9G05vcbwDwt/z5nh9VAHThrgReft/ZXDK41zklRiT4RJqws7TGwRwW9w6kWXOMtkEGniK97Baer0k6YBzuSmNmYF+aHpwxGRTz/eUeZw32iHj3gBZxZF4EaiAnmpSgARxjnPAd55ZwWf0WXS0wBEDQk97VPDauhnr+c=,iv:lInZ9VMfST8v0lRkEdcaNFBydmbgit2YBVLFJbqDU5I=,tag:AMJ79aFK2TMZIPidIG4rgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
