namespace: backend

deployment:
  strategy:
    type: RollingUpdate

replicaCount: 1

image:
  repository: docker.io/datawire/quote
  pullPolicy: IfNotPresent
  tag: "0.5.0"

resources:
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "50m"
    memory: "75Mi"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ingress-traefik
  host: quote.staging.k8s.webgrip.nl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  tls:
    enabled: true
    secretName: letsencrypt-traefik-quote
  paths:
    - path: /
      pathType: Prefix
      port: 80

#readinessProbe:
#  path: /readyz
#  initialDelaySeconds: 5
#  periodSeconds: 10
#
#livenessProbe:
#  path: /healthz
#  initialDelaySeconds: 10
#  periodSeconds: 20
