namespace: arc-systems

gha-runner-scale-set-controller:
  replicaCount: 1

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cpu"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "dedicated"
                operator: "In"
                values:
                  - "cpu"
