namespace: arc-systems

gha-runner-scale-set:
  githubConfigSecret: gha-runner-scale-set-secrets-secret
  githubConfigUrl: https://github.com/webgrip
  minRunners: 1
  maxRunners: 5
  runnerGroup: Default
  runnerScaleSetName: arc-runner-set
  containerMode:
    type: dind
  template:
    spec:
      containers:
        - name: runner
          image: webgrip/github-action-runner:daa31809a3928f3c3cb6d73a1404dcc771435a01
          command: [ "/home/runner/run.sh" ]
