namespace: arc-systems

gha-runner-scale-set:
  githubConfigSecret: gha-runner-scale-set-secrets-secret
  githubConfigUrl: https://github.com/webgrip
  minRunners: 1
  maxRunners: 5
  runnerGroup: Default
  runnerScaleSetName: arc-runner-set
#  containerMode:
#    type: dind
  template:
    spec:
      initContainers:
      - name: init-dind-externals
        image: webgrip/github-action-runner:daa31809a3928f3c3cb6d73a1404dcc771435a01
        command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      containers:
      - name: runner
        image: webgrip/github-action-runner:daa31809a3928f3c3cb6d73a1404dcc771435a01
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
          - -registry-mirror=http://docker-registry.docker-registry.svc.cluster.local:5000
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
      volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
