namespace: arc-systems

gha-runner-scale-set:
  githubConfigSecret: gha-runner-scale-set-secrets
  githubConfigUrl: https://github.com/webgrip
  minRunners: 1
  maxRunners: 5
  runnerGroup: Default
  runnerScaleSetName: arc-runner-set
