namespace: grafana-stack

grafana:
  replicas: 2

  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  ingress:
    enabled: true
    ingressClassName: ingress-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
    tls:
      - secretName: letsencrypt-prod-grafana
        hosts:
          - grafana.staging.k8s.webgrip.nl
    hosts:
      - grafana.staging.k8s.webgrip.nl

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#configuration-options
    server:
      root_url: https://grafana.staging.k8s.webgrip.nl
    auth.github:
      enabled: true
      scopes: user:email,read:org
      allow_sign_up: true
      allowed_organizations: ["webgrip"]
      role_attribute_path: "contains(groups[*], '@webgrip/grafana') && 'GrafanaAdmin' || 'Editor'"
      role_attribute_strict: true
      allow_assign_grafana_admin: true

  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
  envValueFrom:
    GF_AUTH_GITHUB_CLIENT_ID:
      secretKeyRef:
        name: grafana-github
        key: client-id
    GF_AUTH_GITHUB_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-github
        key: client-secret

  persistence:
    storageClassName: do-block-storage
    enabled: true
    size: 10Gi

  plugins:
    - grafana-lokiexplore-app
    - grafana-exploretraces-app
    - grafana-pyroscope-app
    - alexanderzobnin-zabbix-app

  service:
    type: ClusterIP
    port: 80

  datasources:
    datasources.yml:
      apiVersion: 1
      datasources:
        - name: grafana-stack-loki
          uid: grafana-stack-loki
          type: loki
          access: proxy
          url: http://loki.grafana-stack.svc.cluster.local:3100
          editable: true
          jsonData:
            maxLines: 1000
            derivedFields:
              - datasourceUid: grafana-stack-tempo
                matcherType: label
                matcherRegex: trace_id
                name: TraceID
                # url will be interpreted as query for the datasource
                url: '$${__value.raw}'
                urlDisplayLabel: 'View Trace'
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "fake"

        - name: grafana-stack-tempo
          uid: grafana-stack-tempo
          type: tempo
          access: proxy
          url: http://tempo.grafana-stack.svc.cluster.local:3100
          editable: true
          jsonData:
            tracesToLogsV2:
              datasourceUid: 'grafana-stack-loki'
              spanStartTimeShift: '-1h'
              spanEndTimeShift: '1h'
              filterByTraceID: false
              filterBySpanID: false
              customQuery: true
              query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
              tags:
                - key: 'service.name'
                  value: 'service_name'

        - name: kube-prometheus-stack-prometheus
          uid: kube-prometheus-stack-prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090
          editable: true
