namespace: firefly-iii-application

_shared_config:
  hostname: &hostname firefly-iii-application.staging.k8s.webgrip.nl
  url: &url https://firefly-iii-application.staging.k8s.webgrip.nl

application:
  enabled: true
  image:
    repository: webgrip/firefly-iii-application
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    className: ingress-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
    #      traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-ryan-basic-auth@kubernetescrd"
    hosts:
      - host: *hostname
        paths:
          - "/"
    tls:
      - secretName: letsencrypt-firefly-iii-application
        hosts:
          - *hostname
