apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
