namespace: arc-systems

gha-runner-scale-set:
  githubConfigSecret: gha-runner-scale-set-secrets-secret
  githubConfigUrl: https://github.com/webgrip
  minRunners: 1
  maxRunners: 5
  runnerGroup: Default
  runnerScaleSetName: arc-runner-set-k8s
  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
      storageClassName: "dynamic-blob-storage"
      resources:
        requests:
          storage: 1Gi
    kubernetesModeServiceAccount:
      annotations:
  template:
    spec:
      containers:
      - name: runner
        image: webgrip/github-actions-runner:daa31809a3928f3c3cb6d73a1404dcc771435a01
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "true"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "local-path"
                resources:
                  requests:
                    storage: 1Gi
