site_name: "WebGrip Organisation Public"
site_description: "Repository knowledge base (architecture, data, runtime, operations, onboarding)"

theme:
  name: "material"
  custom_dir: overrides
  # analytics:
  #   gtag: G-FAKE
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sections
    - navigation.tabs.expand
    - navigation.prune
    - toc.follow
    - toc.integrate
    - navigation.top

extra_javascript:
  - javascripts/feedback.js

nav:
  - Home: index.md
  - Overview:
    - Project Overview: overview/project_overview.md
    - Getting Started: overview/getting_started.md
    - Repository Structure: overview/repository_structure.md
  - Platform Architecture:
    - Infrastructure Overview: platform/infrastructure_overview.md
    - Kubernetes Components: platform/kubernetes_components.md
    - Networking & Ingress: platform/networking_ingress.md
    - Monitoring & Observability: platform/monitoring_observability.md
  - Operations:
    - CI/CD Workflows: operations/cicd_workflows.md
    - Deployment Guide: operations/deployment_guide.md
    - Secrets Management: operations/secrets_management.md
    - Tools & Commands: operations/tools_commands.md
  - Catalog Structure:
    - Domains: catalog/domains.md
    - Systems: catalog/systems.md
    - Components: catalog/components.md
    - Resources: catalog/resources.md
  - Development:
    - Local Setup: development/local_setup.md
    - Contributing: development/contributing.md
    - Testing: development/testing.md
  - ADRs:
    - Overview: adrs/overview.md
    - All Decisions: adrs/all_decisions.md
  - Reference:
    - Glossary: reference/glossary.md
    - Troubleshooting: reference/troubleshooting.md
    - Maintenance: reference/maintenance.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core:
      use_material_search: true
  - search
  - mermaid2:
      arguments:
        securityLevel: "loose"
  - macros

markdown_extensions:
  - markdown_inline_mermaid

extra:
  # analytics:
  #   provider: custom
  #   property: G-FAKE
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to gather insights into our site's traffic and to ensure you're able to leave feedback.
      If you do not wish to leave feedback or be tracked, feel free to reject the cookies :)

      Thank you for visiting!
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics: Google Analytics
      github: Github
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/organisation
  generator: false

copyright: >
  organisation © 2013 - 2025 Building Better Developers  -
  <a href="#__consent">Change cookie settings</a>
