namespace: ingress-traefik

traefik:
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"

  globalArguments:
    - "--global.checknewversion"
    - "--global.sendanonymoususage=false"

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress-traefik

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    websecure:
      middlewares:
        - "ingress-traefik-ryan-home-ip-allow-list@kubernetescrd"
      forwardedHeaders:
        insecure: false
        trustedIPs:
          - "10.110.0.0/20"
      proxyProtocol:
        insecure: false
        trustedIPs:
          - "10.110.0.0/20"
      http3:
        enabled: true

  logs:
    general:
      level: INFO
    access:
      enabled: true
      fields:
        general:
          defaultMode: keep
        headers:
          defaultMode: keep
