{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart.fullname" . }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.example.com`)
      kind: Rule
      middlewares:
        - name: secure-headers
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: {{ .Values.entryPoints.websecure.http.tls.certResolver }}
{{- end }}
