apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.acmeServer }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretName }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.email }}   # (optional, may not be needed for token-based auth)
            apiTokenSecretRef:
              name: {{ .Values.cloudflareSecretName }}
              key:  {{ .Values.cloudflareSecretKey }}