apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.acmeServer }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretName }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.email }}
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
