{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-chart.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "traefik-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
