{{- if and .Values.middlewares.basicAuth.enabled .Values.middlewares.basicAuth.secret }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.basicAuth.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
spec:
  basicAuth:
    {{- if .Values.middlewares.basicAuth.secret }}
    secret: {{ .Values.middlewares.basicAuth.secret }}
    {{- end }}
{{- end }}