{{- if .Values.middlewares.ipAllowLists }}
{{- range .Values.middlewares.ipAllowLists }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "chart.selectorLabels" $ | nindent 4 }}
spec:
  ipAllowList:
    sourceRange:
{{- range .sourceRanges }}
      - {{ . }}
{{- end }}
---
{{- end }}
{{- end }}
