{{- if and .Values.middlewares.ipAllowList.enabled .Values.middlewares.ipAllowList.sourceRanges }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.ipAllowList.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
spec:
  ipAllowList:
    sourceRange:
{{- range $range := .Values.middlewares.ipAllowList.sourceRanges }}
    - {{ $range }}
{{- end }}
{{- end }}
