{{- if .Values.middlewares.rateLimit.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.rateLimit.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
spec:
  rateLimit:
    average: {{ .Values.middlewares.rateLimit.average | default 100 }}
    burst: {{ .Values.middlewares.rateLimit.burst | default 200 }}
    # Possibly define period, etc. See Traefik docs
{{- end }}
