{{- if .Values.middlewares.securityHeaders.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middlewares.securityHeaders.name }}
  namespace: {{ .Values.namespace }}
spec:
  headers:
    stsSeconds: {{ default 31536000 .Values.middlewares.securityHeaders.stsSeconds }}
    stsIncludeSubdomains: {{ default true .Values.middlewares.securityHeaders.stsIncludeSubdomains }}
    stsPreload: {{ default true .Values.middlewares.securityHeaders.stsPreload }}

    # Common safe headers
    referrerPolicy: {{ default "no-referrer-when-downgrade" .Values.middlewares.securityHeaders.referrerPolicy | quote }}
    contentTypeNosniff: {{ default true .Values.middlewares.securityHeaders.contentTypeNosniff }}
    browserXssFilter: {{ default true .Values.middlewares.securityHeaders.browserXssFilter }}
    forceSTSHeader: {{ default true .Values.middlewares.securityHeaders.forceSTSHeader }}
    frameDeny: {{ default true .Values.middlewares.securityHeaders.frameDeny }}

    # Reasonable default Permissions-Policy
    permissionsPolicy: {{ default "geolocation=(), microphone=(), camera=()" .Values.middlewares.securityHeaders.permissionsPolicy | quote }}

    # CSP
    {{- if .Values.middlewares.securityHeaders.contentSecurityPolicy }}
    contentSecurityPolicy: {{ .Values.middlewares.securityHeaders.contentSecurityPolicy | quote }}
    {{- end }}
---
{{- end }}
