namespace: ingress-traefik

middlewares:
  ipAllowLists:
    - name: ryan-home-ip-allow-list
      sourceRanges:
        - "188.89.91.129/32"
    - name: office-ip-allow-list
      sourceRanges:
        - "92.68.230.153/32"
    - name: allow-all
      sourceRanges:
        - "0.0.0.0/0"
        - "::/0"

  basicAuth:
    enabled: true
    name: ryan-basic-auth
    secret: ryan-basic-auth-secret

  rateLimit:
    enabled: false
    name: my-ratelimit
    average: 100
    burst: 200
