apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: echo-component
  namespace: webgrip
  title: Echo
  description: |
    Echo is a simple HTTP server that responds with the request headers. It is useful for debugging and testing.
  labels:
    tier: "3"
  annotations:
    backstage.io/adr-location: docs/adr
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=echo"
    backstage.io/kubernetes-namespace: backend
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: jmalloc/echo-server
spec:
  type: service
  owner: group:webgrip/infrastructure
  lifecycle: experimental
  system: kubernetes-system
  dependsOn:
    - resource:webgrip/staging-doks-cluster
