apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx-component
  namespace: webgrip
  title: Ingress Nginx
  description: |
    Ingress Nginx is an Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer.
  labels:
    tier: "2"
  annotations:
    backstage.io/adr-location: docs/adr
    github.com/project-slug: kubernetes/ingress-nginx
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=ingress-nginx"
    backstage.io/kubernetes-namespace: ingress-nginx
    simpleicons.org/icon-slug: nginx
spec:
  type: service
  owner: group:webgrip/infrastructure
  lifecycle: experimental
  system: kubernetes-system
