apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quote-component
  namespace: webgrip
  title: Quote
  description: |
    Quote is a simple HTTP server that responds with a random quote. It is useful for testing and learning.
  labels:
    tier: "3"
  annotations:
    backstage.io/adr-location: docs/adr
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=quote"
    backstage.io/kubernetes-namespace: backend
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: datawire/quote
spec:
  type: service
  owner: group:webgrip/infrastructure
  lifecycle: experimental
  system: kubernetes-system
  dependsOn:
    - resource:webgrip/staging-doks-cluster
