name: "[Call] Create New Application"

on:
  workflow_call:
    inputs:
      application_name:
        description: "the name of the application (new repo name)"
        required: true
        type: string
    secrets:
      WEBGRIP_CI_CLIENT_ID:
        description: "GitHub App ID (numeric)"
        required: true
      WEBGRIP_CI_APP_PRIVATE_KEY:
        description: "GitHub App private key (PEM)"
        required: true
      OPENAI_API_KEY:
        description: "OpenAI API key"
        required: true
      OPENAI_ORG_ID:
        description: "OpenAI Organization ID"
        required: true

jobs:
  create-repo-from-template:
    name: ${{ inputs.application_name }}
    uses: webgrip/workflows/.github/workflows/setup-repository-create-from-template.yml@main
    with:
      template_owner: ${{ github.repository_owner }}
      template_repo: 'application-template'
      new_repo_name: ${{ inputs.application_name }}
      visibility: 'public'
      topics: 'action'
    secrets:
        WEBGRIP_CI_CLIENT_ID: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
        WEBGRIP_CI_APP_PRIVATE_KEY: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}

  bootstrap-repo:
    name: ${{ inputs.application_name }}
    uses: webgrip/workflows/.github/workflows/setup-repository-bootstrap.yml@main
    needs: create-repo-from-template
    with:
      repo_name: ${{ inputs.application_name }}
      delete_files: 'CHANGELOG.md'
      replace_values: |
        organisation: ${{ github.repository_owner }}
        application-application: ${{ inputs.application_name }}
      force_commit_files: 'ops/secrets/application-application-secrets/values.dec.yaml'
      configure_pages: true
    secrets:
      WEBGRIP_CI_CLIENT_ID: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
      WEBGRIP_CI_APP_PRIVATE_KEY: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}

  bootstrap-copilot:
    name: ${{ inputs.application_name }}
    uses: webgrip/workflows/.github/workflows/setup-repository-bootstrap.yml@main
    needs: bootstrap-repo
    with:
      repo_name: ${{ inputs.application_name }}
    secrets:
      WEBGRIP_CI_CLIENT_ID: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
      WEBGRIP_CI_APP_PRIVATE_KEY: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
