name: "[Workflow] On Source Change"

on:
  push:
    branches:
      - main
    paths:
      - 'ops/helm/**'
      - 'ops/secrets/**'

concurrency:
  group: push-${{ github.branch }}
  cancel-in-progress: true

jobs:
  determine-changed-secrets:
    name: "Secrets"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@ubuntu-latest
    with:
      inside-dir: 'ops/secrets'

  deploy-changed-secrets:
    name: "Deploy Changed Secrets"
    needs: [ determine-changed-secrets ]
    if: needs.determine-changed-secrets.outputs.matrix != '[]'
    uses: webgrip/workflows/.github/workflows/helm-charts-deploy.yml@ubuntu-latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    with:
      paths: ${{ needs.determine-changed-secrets.outputs.matrix }}


  determine-changed-helm:
    name: "Helm"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@ubuntu-latest
    with:
      inside-dir: 'ops/helm'

  deploy-changed-helm:
    name: "Deploy Changed Services"
    needs: [ determine-changed-helm, deploy-changed-secrets ]
    if: >
      always()
      && needs.determine-changed-helm.outputs.matrix != '[]'
      && needs.deploy-changed-secrets.result == 'success' || needs.deploy-changed-secrets.result == 'skipped'
    uses: webgrip/workflows/.github/workflows/helm-charts-deploy.yml@ubuntu-latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
    with:
      paths: ${{ needs.determine-changed-helm.outputs.matrix }}
