apiVersion: v2
name: gha-runner-scale-set
description: A Helm chart to deploy the GitHub Actions Runner Scale Set
type: application
version: 0.1.0
appVersion: "0.10.1"
dependencies:
  - name: gha-runner-scale-set
    version: 0.10.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
