namespace: arc-systems

gha-runner-scale-set:
  githubConfigSecret: gha-runner-scale-set-secrets
  githubConfigUrl: https://github.com/webgrip
  minRunners: 2
  maxRunners: 10
  runnerGroup: Default
  runnerScaleSetName: arc-runner-set
  #  containerMode:
  #    type: dind
  template:
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "cpu"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dedicated"
                    operator: "In"
                    values:
                      - "cpu"
      initContainers:
        - name: init-dind-externals
#          image: ghcr.io/actions/actions-runner:latest
          image: webgrip/github-runner:latest
          command: [ "cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/" ]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
      containers:
        - name: runner
#          image: ghcr.io/actions/actions-runner:latest
          image: webgrip/github-runner:latest
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          command: [ "/home/runner/run.sh" ]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///var/run/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
            - name: dind-externals
              mountPath: /home/runner/externals
      volumes:
        - name: work
          emptyDir: { }
        - name: dind-sock
          emptyDir: { }
        - name: dind-externals
          emptyDir: { }
  listenerTemplate:
    spec:
      containers:
        - name: listener
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "cpu"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dedicated"
                    operator: "In"
                    values:
                      - "cpu"
